### PR TITLE
Merge pull request #2 from peterboro/main

### PR DESCRIPTION
**Pull request by peterboro**
Merge pull request #1 from peterboro/linter-setup
In this Pull request, I implemented the following elements:

Setup Linters.
Created an HTML File
Added header and style to the HTML File.
Added test.md file to .gitignore
Fixed linter errors.
Modified the README.md file

### CODE REVIEW

**Review by Kandy-Peter — CHANGES_REQUESTED** [review]
Hi @peterboro,

Good job so far! I know you have worked hard on implementing the project and its requirements. However, there is an issue that you still need to work on to go to the next project but you are almost there!

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- You  are following GitHub actions :heavy_check_mark: 
## Required Changes ♻️

- [x] I would suggest you provide a short description in your pull request that summarizes what you did and implemented. You can write something like:
```
In this Pull request, I implemented the following elements:
- Install linters
- Create an HTML file.
- etc
```

- [x] Kindly check the comments under the review.

## Optional suggestions

- [x] Do not close your PR on every requested change. You should open only one pull request for every project(milestone) and use it for each review you will get.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by peterboro** [comment]
In this Pull request, I implemented the following elements:
- Setup Linters.
- Created an HTML File 
- Added header and style to the HTML File.
- Added test.md file to .gitignore
- Fixed linter errors.
- Modified the README.md file

**Review by DammyShittu — CHANGES_REQUESTED** [review]
Hi @peterboro,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
- [x] Instead of adding the summary as requested the previous reviewer as a comment, simply edit the Pull Request summary and add the summary there.

  kyl-pr

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by algerina — APPROVED** [review]
Hi @peterboro , 
Good job so far! 👏🏼 @

May I highlight the following:

- The repo looks good.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous TSEs
 

 ## Optional suggestions
 
 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Pull request merged**
